package com.github.bartoszpogoda.thesis.teamchallengeapi.core.exception;

public enum ExceptionCode {
    UNAUTHORIZED,
    VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_USED,
    FACILITY_NOT_FOUND,
    UNKNOWN_DISCIPLINE,
    PLAYER_ALREADY_EXISTS,
    INTERNAL_SERVER_ERROR,
    PLAYER_NOT_FOUND,
    UNKNOWN_REGION,
    PLAYER_ALREADY_IN_TEAM,
    TEAM_NOT_FOUND,
    TEAM_INVITATION_NOT_FOUND,
    ALREADY_INVITED;
}
