package com.github.bartoszpogoda.thesis.teamchallengeapi.core.exception;

public enum ExceptionCode {
    UNAUTHORIZED,
    VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_USED,
    FACILITY_NOT_FOUND,
    UNKNOWN_DISCIPLINE,
    PLAYER_PROFILE_NOT_FOUND, PLAYER_ALREADY_EXISTS_EXCEPTION, INTERNAL_SERVER_ERROR, PLAYER_NOT_FOUND, PLAYER_PROFILE_ALREADY_EXISTS_EXCEPTION;
}
